[font]
normal = {family= "FiraCode Nerd Font" ,style = "Regular" }
size = 12
builtin_box_drawing = true

[env]
term = "xterm-256color"

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
