[[plugins]]
repo = "tpope/vim-surround"
on_event = "CursorMoved"

[[plugins]]
repo = "junegunn/fzf.vim"
on_cmd = "Files"
#on_key="<leader>ff"
hook_add = '''
nnoremap <Leader>ff :Files<CR>
'''

[[plugins]]
repo="vim-airline/vim-airline"
on_event="BufReadPre"

[[plugins]]
repo="vim-jp/vimdoc-ja"
on_ft ="help"
