[[plugins]]
rEpo = "Shougo/dpp.vim"

[[plugins]]
repo = "Shougo/dpp-ext-lazy"

[[plugins]]
repo = "Shougo/dpp-ext-toml"

[[plugins]]
repo = "Shougo/dpp-ext-installer"

[[plugins]]
repo = "Shougo/dpp-protocol-git"

[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
hooks_file = "$HOOK_DIR/treesitter.lua"
rev = "main"
