toml-version = "v1.0.0"

[files]
include = ["**/*.toml"]

[lsp]
code-action.enabled = true
completion.enabled = true
diagnostics.enabled = true
document-link.enabled = true
formatting.enabled = true
goto-declaration.enabled = true
goto-definition.enabled = true
goto-type-definition.enabled = true
hover.enabled = true
workspace-diagnostic.enabled = true

[schema]
enabled = true
strict = true
catalog = {
  paths = [
    "tombi://json.schemastore.org/api/json/catalog.json",
    "https://json.schemastore.org/api/json/catalog.json",
  ],
}
