snippets:
  # snippet and keyword abbrev
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git log
    keyword: gl
    snippet: git log --graph --oneline --all
  - name: clear
    keyword: clr
    snippet: clear
  - name: "find file"
    keyword: "ff"
    snippet: "$(fd -H -t f -d 6 -E .git | fzf --tmux)"
    context:
      buffer: '.*\s'
  - name: "find dir"
    keyword: "fdi"
    snippet: "$(fd -H -t d -t l -E .git -d 6 | fzf --tmux)"
    context:
      buffer: '.*\s'
completions:
  - name: path
    patterns:
      - "^cd $"
    sourceCommand: "fd --no-ignore-vcs -t d -t l -d 1"
    options:
      --multi: true
    callback: "sed -e 's/^\\.\\///'"
