snippets:
  # snippet and keyword abbrev
  - name: git status
    keyword: gs
    snippet: git status --short
  - name: git log
    keyword: gl
    snippet: git log --graph --oneline --color
  - name: git commit
    keyword: gc
    snippet: git commit
  - name: git add
    keyword: ga
    snippet: git add -A
  - name: git add -p
    keyword: gap
    snippet: git add -p
  - name: cd parrent dir
    keyword: cdr
    snippet: cd ..
  - name: cd prev dir
    keyword: cdb
    snippet: cd -

completions:
  - name: chdir
    patterns:
      - "^cd $"
    sourceCommand: "fd -t d -d 3 -E .git -E .cache -E .direnv"
    options:
      --prompt: "'Chdir> '"
      --preview: "cd {} && ls -a | sed '/^[.]*$/d'"
    callbackZero: true
