SPLIT_FILES="/home/hidehico/.config/zsh/zsh.d"

# hist settings
source "$SPLIT_FILES/hist.zsh"

# p10k settings
source "$SPLIT_FILES/p10k.zsh"

# sheldonの設定
eval "$(sheldon source)"

# 補完で選んでいるところを色付ける設定
zstyle ':completion:*' menu true
zstyle ':completion:*:rm:*' menu false

# rust path
. "$HOME/.cargo/env"

# alias import
source "$SPLIT_FILES/alias.zsh"

# function import
source "$SPLIT_FILES/func.zsh"

