on:
  push:
  pull_request:
jobs:
  run_aqua_install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.43.1
        env:
          AQUA_CONFIG: aqua/aqua.yaml
