on:
  push:
    paths:
      - nvim/
jobs:
  neovim_install_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: copy neovim config
        run: cp -r ${{ github.workspace }}/nvim/ ~/.config/nvim/
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATEKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: install test
        run: nvim --headless "+Lazy! sync" +qa
