name: update nix flake

on:
  schedule:
    - cron: "0 */3 * * *"
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(flake): updated flake.lock"
