login-password: ENC[AES256_GCM,data:OhzSDfeghK+IAcMe5ycE+h297PF+QsDblGpNgdbX7jCkxezFgIQVTqwVWjzgQczGVsbMfni098QqEArQaa4dPHbUaFlf9ROuFCPZirthU1log+ZyKGC2thavU5DwcxoVg1RVJ9Wu19ABUw==,iv:/cR7jyNhcr5BeVjvkIWvCvjx1K2G9oL9cIjR+psdoKo=,tag:hxceAVziDu2tj7a3er0vFw==,type:str]
sops:
  age:
    - recipient: age12ukj4mk4k6umgdz5fyaxjh8ceczufw7wxjgwzj7w450mdhpwfsuqm43g85
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WWU4UTU0b0lpTnUrT2Jl
        TTZGQ1plT2o5MnJoUzBFdFhQZUNhMm9BQTNRCkI5Z2drZ1IxVTA2dTY0R3RwWlBO
        OE4zVHZIWXllUVBKaUJEQUo4WHZDS2sKLS0tIEdWdGlacEN2eGNNakRoRTJkODlX
        THF0Z3NTTGhrSkRrSjdxOC9zWUhNdEUKAuWEO+nw0UUgsg7JhjvENNKMubzhtfZu
        8HU3acwCNv1agdY+sr8XI/5J2+5qwAUm/jJvu/ToEKc/YdkzKa75kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T12:32:21Z"
  mac: ENC[AES256_GCM,data:YZRFyKUnSQ41qzuSn0+DJRgXdLsbhdTvLKV+zgO2Hg/9jetGy0t3AsUZlqbEHggJ5QBMGaYysp7L8BFQiekpoT9kVIPsqs2233qkbUdE+031UWO+CS7dzejKVtCtrQn+PpGYFlHH6sUVfvX63ggjMBFP5JkX9QP0pqToYkYr/1o=,iv:bmE1y9qAMrt5ulmYFKKQa3uha1O+aAt88pB9CWS9Fak=,tag:/gMBpF9cR3YIJ7JXU9P0Og==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
